const ActionsType = {
  // user
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_USER_DETAIL: "SET_USER_DETAIL",
  SET_TOKEN: "SET_TOKEN",
  SET_USER_TYPE: "SET_USER_TYPE",
  SET_ONBAORDING_FLAG: "SET_ONBAORDING_FLAG",
  SET_BECOME_PROVIDER: "SET_BECOME_PROVIDER",
  SET_BADGE_ENABLED: "SET_BADGE_ENABLED",
  SET_USER_MODE: "SET_USER_MODE",
  SET_FILTER_DATA: "SET_FILTER_DATA",
  SET_FILTER_PARAMS: "SET_FILTER_PARAMS",

  //loader
  SET_LOADER: "SET_LOADER",
  SET_CHOOSED_TYPE: "SET_CHOOSED_TYPE",

  //profile
  SET_PROFILE_STATUS: "SET_PROFILE_STATUS",
  SET_REVIEWS: "SET_REVIEWS",
  SET_NOTIFICATION_LIST: 'SET_NOTIFICATION_LIST',
  SET_CHILD_LIST: 'SET_CHILD_LIST',
  LOCATION_LIST: 'LOCATION_LIST',

  //listing
  SET_LISTING_ARRAY: "SET_LISTING_ARRAY",
  SET_SPECIFIC_USER_LIST: "SET_SPECIFIC_USER_LIST",
  SET_ALL_LISTING: "SET_ALL_LISTING",
  SET_SCHEDULE_LIST: "SET_SCHEDULE_LIST",
  SET_POLICY_LIST: "SET_POLICY_LIST",
  SET_LISTING_DETAIL: "SET_LISTING_DETAIL",
  SET_SEARCH_TEXT: "SET_SEARCH_TEXT",

  //tax info
  SET_TAX_INFO: "SET_TAX_INFO",
  SET_NEW_TAX_ADD: "SET_NEW_TAX_ADD",

  //favourites
  SET_FAVOURITES_LIST: "SET_FAVOURITES_LIST",
  SET_FAVOURITES_PROVIDER: "SET_FAVOURITES_PROVIDER",

  //BOOKING
  SET_USER_BOOKING_LIST: "SET_USER_BOOKING_LIST",
  SET_LIST_BOOKING: "SET_LIST_BOOKING",
  SET_BOOKING_DETAIL: "SET_BOOKING_DETAIL",
  SET_PAYMENT_STATS: "SET_PAYMENT_STATS",
  SET_BOOKING_STATS: "SET_BOOKING_STATS",

  API_ERROR: "API_ERROR",
  API_SUCCESS: "API_SUCCESS"
}

export default ActionsType
